# Generated by Django 2.2 on 2019-11-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
